Upload to annotator from disk
michaeliwaikato/ufdl-frontend pull request #4
Opened 2020-08-31 02:22 UTC by andrei-msd

2020-08-31 05:01 UTC, yaserazfar commented on frontend-react/src/components/annotate.js
> -                    regionClsList={["kiwi fruit", "leaf"]}
I am no longer able to add a label to annotations. I think we may need to leave some default annotations or the empty string `regionClsList={[""]}` inside of here.

2020-08-31 05:12 UTC, yaserazfar submitted a review, later dismissed
I think we should also add a TODO comment somewhere in annotate.js to keep us aware of the issue where uploading a new image currently will reset annotations. This probably cannot be fixed until we have made some progress with the JS Client.

Also we can probably make the "upload images" button bigger to improve the UI.

Apart from these minor points, it looks great.

2020-08-31 05:12 UTC, yaserazfar commented on frontend-react/src/components/annotate.js
> +                    regionClsList={[]}
I am no longer able to add a label to annotations. I think we may need to leave some default annotations or the empty string `regionClsList={[""]}`

2020-09-05 21:06 UTC, yaserazfar approved these changes
LGTM.

We need to make adding annotations strings possible without leaving those default values in `regionCLSList` but that can be worked on later and it works for the changes we need right now.

2020-09-08 00:32 UTC, michaeliwaikato requested changes

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        images.push({src: img.src, name: files[i].name});
```suggestion
        images.push({src: img.src, name: files[i].name});
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> -              });
I think this style looks better...

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +    this.setState({uploaded: true});
... than this

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +  }
```suggestion
  }
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        let { uploaded } = this.state;
Same as above.

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +
```suggestion
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +
```suggestion
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +
```suggestion
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +
```suggestion
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        else{
```suggestion
        else {
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +            )
```suggestion
            );
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +
```suggestion
```

2020-09-08 00:32 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +}
We should have newlines at the end of files.

2020-09-17 02:24 UTC, michaeliwaikato approved these changes

2020-09-17 02:26 UTC, merged