my code for login screen
michaeliwaikato/ufdl-frontend pull request #5
Opened 2020-09-12 00:33 UTC by Fajeeer

2020-09-13 05:06 UTC, michaeliwaikato requested changes

2020-09-13 05:06 UTC, michaeliwaikato commented on frontend-react/package.json
> +    "modulo": "0.0.3",
Not really sure what these are used for or if they are even necessary?

2020-09-13 05:06 UTC, michaeliwaikato commented on frontend-react/src/components/landingpage.js
> +import Navigation from '../navigation.js';
Is there any particular reason this is here?

2020-09-13 05:06 UTC, michaeliwaikato commented on frontend-react/src/components/landingpage.js
> +    }
This code is not being used so it shouldn't be here.

2020-09-13 05:06 UTC, michaeliwaikato commented on frontend-react/src/components/landingpage.js
> +                            <label style={{marginRight: "2.5rem"}} for={'port'}>Port</label>
Styling should be applied in style/landingpage.css
The source images should also be given a better name and be put in a new folder such as "resources" or something like that.

2020-09-13 05:06 UTC, michaeliwaikato commented on frontend-react/src/components/landingpage.js
> +}
Same as above, this should be in style/landingpage.css

2020-09-16 09:51 UTC, andrei-msd requested changes

2020-09-16 09:51 UTC, andrei-msd commented on frontend-react/src/components/landingpage.js
> +                    <h1 className="head1">User Friendly and nbsp</h1>
The h1 should be "User Friendly Deep Learning"

2020-09-16 09:51 UTC, andrei-msd commented on frontend-react/src/components/landingpage.js
> +                    <h1 className="head1">User Friendly and nbsp</h1>
```suggestion
                    <h1 className="head1">User Friendly</h1>
```

2020-09-28 23:06 UTC, andrei-msd approved these changes

2020-09-30 04:55 UTC, merged