Andrei react annotator modified
michaeliwaikato/ufdl-frontend pull request #7
Opened 2020-10-03 08:02 UTC by andrei-msd

2020-10-03 08:08 UTC, yaserazfar approved these changes
LGTM. Have tested the functionality with your branch in ufdl-image-annotator. Everything seems to be working.

2020-10-03 08:08 UTC, yaserazfar commented
Don't forget to squash before you merge please hahah

2020-10-04 06:39 UTC, michaeliwaikato requested changes

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        uploaded: false,
This has inconsistent spacing in it (2 vs 4 spaces).

It should probably also be put in a constructor.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +      index: this.state.index = annotateData.selectedImage
It would be good if you could comment this to indicate this is intended to fix an error when the '=' isn't used. (Possibly state the error)

Edit: Probably should take a look at [this](https://reactjs.org/docs/faq-state.html) as it likely fixes some problems
Edits 2: This is definitely a hack and can easily be fixed with a redesign of the logic

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        index: this.state.index = this.state.index - 1
This could be causing problems as indicated above.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +          index: this.state.index = 0
Same as above.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +    }
Probably redundant?

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +  }
Could cause problems with asynchronous nature as above.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +  }
Same again.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +
And again.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +  }
This can fairly easily be shortened and simplified to something like:

`document.getElementById('file').click()`

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +      <div className="border">
```suggestion
      <div id="border">
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        <form className="selectForm">
```suggestion
        <form id="selectForm">
```

Are these forms actually needed anyway?

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +            <input type="file" id="file" multiple={true} accept="image/*" className="fileInputButton" onChange={this.fileSelectedHandler} />
```suggestion
            <input type="file" id="file" multiple={true} accept="image/*" onChange={this.fileSelectedHandler} />
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +            </label>
```suggestion
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        <div className="imageDisplay">
```suggestion
        <div id="imageDisplay">
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +            onExit={output => console.log(JSON.stringify(output.images))}
Spacing etc should be consistent to make it easier to read/understand.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +    );}
```suggestion
    );
  }
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/components/annotate.js
> +        </div>
Same as above in terms of the ids etc.

An idea for this is that this is removed and a base sample image is added to the annotator showing some instructions on how to use. Then the "add image" button is clicked which clears the sample image and shows the users images.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/index.js
> -  </React.StrictMode>,
If you can indicate exactly why this was removed then that would be good.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +
```suggestion
```

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
>  .fileInputButton:focus + .fileLabel {
I can't add comments for the parts above, but these should be ids and not classes.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +  /* max-width: 90vh; */
What are these for?

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +  visibility:hidden;
Redundant.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
> +  visibility: visible;
Redundant.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
>    margin-top: 20%;
Seems a little hacky.

2020-10-04 06:39 UTC, michaeliwaikato commented on frontend-react/src/style/annotate.css
>  .imageDisplay {
Same as above.

2020-10-27 02:43 UTC, merged